config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions'
    # passwords:     'admins/passwords',
    # registrations: 'admins/registrations'
  }

  scope module: :public do
    get 'customers/quit'  => 'customers#quit', as: 'customers_quit'
    patch 'customers/out' => 'customers#out', as: 'customers_out'
    get 'orders/comfirm'  => 'orders#comfirm'
    get 'orders/thanks'   => 'orders#thanks'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'

    resources :customers,  only:[:show, :edit, :update]
    resources :addresses,  only:[:index, :edit, :create, :update, :destroy]
    resources :items,      only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    resources :orders,     only:[:new, :create, :index, :show]

  end

  namespace :admin do
    root 'homes#top'
    resources :genres,        only:[:index, :create, :edit, :update, :destroy]
    resources :items,         only:[:index, :new, :create, :show, :edit, :update]
    resources :customers,     only:[:index, :show, :edit, :update]
    resources :orders,        only:[:show, :update]
    resources :order_details, only:[:update]
  end
end

app/models/item.rb
class Item < ApplicationRecord

  validates :name , presence: true
  validates :introduction , presence: true
  validates :price , presence: true
  validates :image , presence: true

  attachment :image

  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.search_for(content)
    #.orを使用することで、contentに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    Item.where('name LIKE ?', '%'+content+'%').or(Item.where(genre_id: content))
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all

  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <h5 class="title2">商品編集画面</h5>
  <div class="row">
    <div class="col mx-auto">

      <%= form_with model: @item, url: admin_item_path(@item), local: true do |f| %>

        <form class="form-horizontal">
          <div class="form-group">
            <%= f.label :image, '商品画像', class: "form-label, col-2" %>
            <%= f.attachment_field :image, class: "form-control, col-4" %>
          </div>

          <div class="form-group">
            <%= f.label :name, '商品名', class: "form-label, col-2" %>
            <%= f.text_field :name, class: "form-control, col-4" %>
          </div>

          <div class="form-group">
            <%= f.label :introduction, '商品説明', class: "form-label, col-2" %>
            <%= f.text_area :introduction, class: "form-control, col-4" %>
          </div>

          <div class="form-group">
            <%= f.label :genre_id, 'ジャンル', class: "form-label, col-2" %>
            <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "カテゴリを選択してください", class: "form-control, col-4" %>
          </div>

          <div class="form-group">
            <%= f.label :price, '税抜価格', class: "form-label, col-2" %>
            ￥<%= f.text_field :price, class: "form-control, col-2" %>
          </div>

          <div class="form-group">
            <%= f.label :is_active, '販売ステータス', class: "form-label, col-2" %>
            <%= f.select :is_active, [['販売中', true], ['販売停止', false]], include_blank: "選択してください", class: "form-control, col-4" %>
          </div>

          <div class="actions">
            <%= f.submit "変更を保存", class: "btn btn-info" %>
          </div>

        </form>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col">
      <h5 class="title mb-3">商品一覧</h5>
      <p class="text-right"><%= link_to "商品新規登録", new_admin_item_path, class: "btn btn-info" %></p>

      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th></th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th>ジャンル</th>
            <th>販売ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to admin_item_path(item) do %>
                      <%= attachment_image_tag item, :image, format: 'jpeg', size:"100x100" %>
                  <% end %>
              </td>
              <td><%= link_to item.name, admin_item_path(item) %></td>
              <td>¥<%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active == true %>
                  <p>販売中</p>
                <% else %>
                  <p>販売停止中</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h5 class="title2">商品新規登録</h5>
  <div class="row align-items-center">
    <div class="col">

      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>

      <form class="form-horizontal">

        <div class="form-group">
          <%= f.label :image, '商品画像', class: "form-label, col-2" %>
          <%= f.attachment_field :image, class: "form-control, col-4" %>
        </div>

        <div class="form-group">
          <%= f.label :name, '商品名', class: "form-label, col-2" %>
          <%= f.text_field :name, class: "form-control, col-4" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction, '商品説明', class: "form-label, col-2" %>
          <%= f.text_area :introduction, class: "form-control, col-4" %>
        </div>

        <div class="form-group">
          <%= f.label :genre_id, 'ジャンル', class: "form-label, col-2" %>
          <%= f.collection_select :genre_id, @genres, :id, :name, :include_blank => "カテゴリを選択してください", class: "form-control, col-4" %>
        </div>

        <div class="form-group">
          <%= f.label :price, '税込価格', class: "form-label, col-2" %>
          ¥<%= f.text_field :price, class: "form-control, col-2" %>
        </div>

        <div class="form-group">
          <%= f.label :is_active, '販売ステータス', class: "form-label, col-2" %>
          <%= f.select :is_active, [['販売中', true], ['販売停止', false]], include_blank: "選択してください", class: "form-control, col-4" %>
        </div>

        <div class="actions">
          <%= f.submit "新規登録", class: "btn btn-info" %>
        </div>

      </form>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="title2">商品詳細</h5>
  </div>

  <div class="row">

    <div class="col-3">
      <%= attachment_image_tag @item, :image, format: 'jpeg', size:"100x100" %>
    </div>

    <div class="col-9">
      <table>
        <tr class="height: 10%">
          <td style="width: 35%">商品名</td>
          <td style="width: 60%"><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込み価格 <br>（税抜き価格）</td>
          <td>
            ¥<%= @item.add_tax_price.to_s(:delimited) %> <br>
            ¥<%= @item.price.to_s(:delimited) %>
          </td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active == true %>
              <strong class="text-success">販売中</strong>
            <% elsif @item.is_active == false %>
              <strong class="text-success">販売停止中</strong>
            <% end %>
          </td>
        </tr>
      </table>

      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>

    </div>
  </div>
</div>