config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions'
    # passwords:     'admins/passwords',
    # registrations: 'admins/registrations'
  }

  scope module: :public do
    get 'customers/quit'  => 'customers#quit', as: 'customers_quit'
    patch 'customers/out' => 'customers#out', as: 'customers_out'
    get 'orders/comfirm'  => 'orders#comfirm'
    get 'orders/thanks'   => 'orders#thanks'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'

    resources :customers,  only:[:show, :edit, :update]
    resources :addresses,  only:[:index, :edit, :create, :update, :destroy]
    resources :items,      only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    resources :orders,     only:[:new, :create, :index, :show]

  end

  namespace :admin do
    root 'homes#top'
    resources :genres,        only:[:index, :create, :edit, :update, :destroy]
    resources :items,         only:[:index, :new, :create, :show, :edit, :update]
    resources :customers,     only:[:index, :show, :edit, :update]
    resources :orders,        only:[:show, :update]
    resources :order_details, only:[:update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name , presence: true
  validates :last_name , presence: true
  validates :first_name_kana , presence: true
  validates :last_name_kana , presence: true
  validates :telephone_number , presence: true
  validates :postal_code , presence: true
  validates :address , presence: true
  validates :email , presence: true, length: { maximum: 300 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  def active_for_authentication?
    super && (is_active == true)
  end

  def full_name
    "#{last_name}#{first_name}"
  end

  def full_kana
    "#{last_name_kana}#{first_name_kana}"
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.order(created_at: "DESC")
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_active == false)
        flash[:notice] = "アカウントが見つかりません。会員登録をしてご利用ください。"
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10, mx-auto, container-fluid">
      <h5 class="title3"><%= @customer.full_name %>さんの会員情報編集</h5>

      <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>

        <form class="form-horizontal">

          <div class="form-group col-9">
            <%= f.label "会員ID" %>
            <%= f.label :"#{@customer.id}" %>
          </div>

          <div class="form-group col-9">
            <%= f.label "氏名", class: "form-label, col-3" %>
            <%= f.text_field :last_name, class: "form-control, col-4" %>
            <%= f.text_field :first_name, class: "form-control, col-4" %>
          </div>

          <div class="form-control, col-9">
            <%= f.label "フリガナ", class: "form-label, col-3" %>
            <%= f.text_field :last_name_kana, class: "form-control, col-4" %>
            <%= f.text_field :first_name_kana, class: "form-control, col-4" %>
          </div>

          <div class="form-control, col-9">
            <%= f.label "郵便番号", class: "form-label, col-3" %>
            <%= f.text_field :postal_code, class: "form-control, col-4" %>
          </div>

          <div class="form-control, col-9">
            <%= f.label :住所, class: "form-label, col-3" %>
            <%= f.text_field :address, class: "form-control, col-4" %>
          </div>

          <div class="form-control, col-9">
            <%= f.label "電話番号", class: "form-label, col-3" %>
            <%= f.text_field :telephone_number, class: "form-control, col-4" %>
          </div>

          <div class="form-control, col-9">
            <%= f.label "メールアドレス", class: "form-label, col-3" %>
            <%= f.email_field :email, class: "form-control, col-4" %>
          </div>

          <div class="form-control, col-9">
            <p class="form-label, col-3">会員ステータス</p>
            <%= f.radio_button :is_active, :true, checked: true %>
            <%= f.label :is_active, '有効' %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, '退会' %>
          </div>

          <div class="actions">
          <%= f.submit "変更を保存", class: "btn btn-info" %>
          </div>

        </form>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10, mx-auto, container-fluid">
      <h5 class="title">会員一覧</h5>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.full_name, admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active == true %>
                <p>有効</p>
              <% else %>
                <p>退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class= "col-6">
      <h5 class="title3"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h5>

      <table class="table, ml-10">
        <tr>
          <td style="width: 35%">会員ID</td>
          <td style="width: 35%"><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name %>  <%= @customer.first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.last_name_kana %>  <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.telephone_number %></td>
        </tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <% if @customer.is_active == true %>
              <strong class="text-success">有効</strong>
            <% else %>
              <strong class="text-success">退会</strong>
            <% end %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-info" %></td>
          <td><%= link_to "注文履歴一覧へ", admin_root_path, class: "btn btn-success" %></td>
        </tr>
      </table>

    </div>
  </div>
</div>