config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions'
    # passwords:     'admins/passwords',
    # registrations: 'admins/registrations'
  }

  scope module: :public do
    get 'customers/quit'  => 'customers#quit', as: 'customers_quit'
    patch 'customers/out' => 'customers#out', as: 'customers_out'
    get 'orders/comfirm'  => 'orders#comfirm'
    get 'orders/thanks'   => 'orders#thanks'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'

    resources :customers,  only:[:show, :edit, :update]
    resources :addresses,  only:[:index, :edit, :create, :update, :destroy]
    resources :items,      only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    resources :orders,     only:[:new, :create, :index, :show]

  end

  namespace :admin do
    root 'homes#top'
    resources :genres,        only:[:index, :create, :edit, :update, :destroy]
    resources :items,         only:[:index, :new, :create, :show, :edit, :update]
    resources :customers,     only:[:index, :show, :edit, :update]
    resources :orders,        only:[:show, :update]
    resources :order_details, only:[:update]
  end
end

app/models/order.rb
class Order < ApplicationRecord

  enum method_of_payment: {クレジットカード: 0, 銀行振込: 1}
  enum order_status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :name, presence: true

  def date_full
    created_at.strftime('%Y/%m/%d %H:%M:%S')
  end

  def date
    created_at.strftime('%Y/%m/%d')
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order.postage = 800
    @order_detail = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_status = params[:order][:order_status].to_i
    @order.update(order_status: @order_status)
    if @order_status == 1
      @order.order_details.each do |order_detail|
        order_detail.update(production_status: 1)
      end
    end
    redirect_to admin_order_path(@order)
  end

  def customer_index
    @orders = Order.where(customer_id: params[:customer_id]).order(cerated_at: "DESC")
  end

  private

  def order_status_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="title2">注文履歴詳細</h5>
  </div>

  <div class="row">
    <div class="col-8 mb-5">

      <table>
        <tr>
          <td style="width: 10%">購入者</td>
          <td style="width: 35%"><%= link_to @order.customer.full_name, admin_customer_path(@order.customer) %></td>
        </tr>
        <tr>
          <td>注文日</td>
          <td><%= @order.date_full %></td>
        </tr>
        <tr>
          <td>配送先</td>
          <td>
            <%= @order.shipping_postal_code %> <%= @order.shipping_address %> <br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <td>支払い方法</td>
          <td><%= @order.method_of_payment %></td>
        </tr>
        <tr>
          <td>注文ステータス</td>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
              <%= f.select :order_status, options_for_select(Order.order_statuses, selected: Order.order_statuses[@order.order_status]) %>
              <%= f.submit "更新", class: "btn-info #{ "disabled" if @condition_order }" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <table class="table">
        <thead>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </thead>

        <tbody>
          <% @order_detail.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td>¥<%= order_detail.price.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td>¥<%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch,  local: true do |f| %>
                  <%= f.select :production_status, options_for_select(OrderDetail.production_statuses, selected: OrderDetail.production_statuses[order_detail.production_status]) %>
                  <%= f.submit "更新", class: "btn-info #{ "disabled" if @condition_detail }" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-4">
      <table>
        <tr>
          <td style="width: 50%">合計金額</td>
          <td style="width: 40%">¥<%= (@order.billing_amount.to_i - @order.postage).to_s(:delimited) %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td>¥800</td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td>¥<%= @order.billing_amount.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>

  </div>
</div>