config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions'
    # passwords:     'admins/passwords',
    # registrations: 'admins/registrations'
  }

  scope module: :public do
    get 'customers/quit'  => 'customers#quit', as: 'customers_quit'
    patch 'customers/out' => 'customers#out', as: 'customers_out'
    get 'orders/comfirm'  => 'orders#comfirm'
    get 'orders/thanks'   => 'orders#thanks'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'

    resources :customers,  only:[:show, :edit, :update]
    resources :addresses,  only:[:index, :edit, :create, :update, :destroy]
    resources :items,      only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    resources :orders,     only:[:new, :create, :index, :show]

  end

  namespace :admin do
    root 'homes#top'
    resources :genres,        only:[:index, :create, :edit, :update, :destroy]
    resources :items,         only:[:index, :new, :create, :show, :edit, :update]
    resources :customers,     only:[:index, :show, :edit, :update]
    resources :orders,        only:[:show, :update]
    resources :order_details, only:[:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name , presence: true
  validates :postal_code , presence: true
  validates :address , presence: true

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  def add_tax_price
    (self.item.price*1.10).round
  end

  def sub_price
    add_tax_price*self.amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name , presence: true
  validates :last_name , presence: true
  validates :first_name_kana , presence: true
  validates :last_name_kana , presence: true
  validates :telephone_number , presence: true
  validates :postal_code , presence: true
  validates :address , presence: true
  validates :email , presence: true, length: { maximum: 300 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  def active_for_authentication?
    super && (is_active == true)
  end

  def full_name
    "#{last_name}#{first_name}"
  end

  def full_kana
    "#{last_name_kana}#{first_name_kana}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name , presence: true
  # attachment :image

end

app/models/item.rb
class Item < ApplicationRecord

  validates :name , presence: true
  validates :introduction , presence: true
  validates :price , presence: true
  validates :image , presence: true

  attachment :image

  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.search_for(content)
    #.orを使用することで、contentに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    Item.where('name LIKE ?', '%'+content+'%').or(Item.where(genre_id: content))
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum method_of_payment: {クレジットカード: 0, 銀行振込: 1}
  enum order_status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :name, presence: true

  def date_full
    created_at.strftime('%Y/%m/%d %H:%M:%S')
  end

  def date
    created_at.strftime('%Y/%m/%d')
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum production_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

  belongs_to :item
  belongs_to :order

  validates :price, presence: true
  validates :amount, presence: true

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @order = Order.all.order(created_at: "DESC")
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all

  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin
        admin_root_path
      when Customer
        root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected
  def configure_permitted_parameters
    added_attrs = [:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,
                    :address,:telephone_number, :email]

    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_active, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address])

    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
    @item = Item.find_by(params[:id])
    @genres = Genre.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-warning" >
        <!--アイコン部分-->
        <%= link_to root_path do %>
          <%= image_tag"img/nagano_cake.jpg",class:"navbar-brand" %>
        <% end %>
        <!--ハンバーガー部分-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!--ナビゲーションメニュー-->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to "お店の紹介", about_path, class: "btn btn-danger" %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: "btn btn-success" %>
              </li>
              <li class="nav-item">
                <%= link_to "カートリスト", cart_items_path, class: "btn btn-primary" %>
              </li>
              <li class="nav-item">
                <%= link_to "マイページ", customer_path(current_customer), class: "btn btn-success" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path,method: :delete, class: "btn btn-dark" %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-success" %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-primary" %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-danger" %>
              </li>
              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-info" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-dark" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "お店の紹介", about_path, class: "btn btn-danger" %>
              </li>
              <li class="nav-item">
                <%= link_to " 商品一覧", items_path, class: "btn btn-success" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-secondary" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: "btn btn-dark" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>